models:
  - name: bronze_raw_loans
    columns:
      - name: income_str
        tests:
          - not_null
version: 2
models:
  - name: bronze_raw_loans
    columns:
      - name: credit_score
        tests:
          - not_null